### ISSUE TITLE
Image Files needed

### ISSUE THREAD

**Issue by reggi** [reggi/wordpress-savory#1]
- [x] Social Icons
- [x] Lotus Icon

**Comment by gdamatodesign** [comment]
Social Icons as .png attached here - 

![facebook](https://cloud.githubusercontent.com/assets/11381038/6548163/50265ef4-c5c6-11e4-8596-9860e4e5753d.png)
![tumblr](https://cloud.githubusercontent.com/assets/11381038/6548164/5026902c-c5c6-11e4-99e3-94df84a93c37.png)
![twitter](https://cloud.githubusercontent.com/assets/11381038/6548162/5025a554-c5c6-11e4-99a4-e472243c00d6.png)

**Comment by gdamatodesign** [comment]
Lotus_Dark.svg has been dropped here: 
https://www.dropbox.com/s/5dp8y4f2xd1x1jt/Lotus_dark.svg?dl=0

Lotus_white.svg has been dropped here:
https://www.dropbox.com/s/x6yd6yq2h430k2o/Lotus_white.svg?dl=0

**Comment by gdamatodesign** [comment]
The lotus image is currently being vetted. When it does change, can you let me know what the best file format is?

**Comment by reggi** [comment]
Perfecto! Thanks a bunch @gdamatodesign. 

Ideally  `.png` does it need to be fancy?

**Comment by gdamatodesign** [comment]
.png it is! I'll have one by EOD

**Comment by reggi** [comment]
In the mockup for the social buttons you include twitter twice.

**Comment by gdamatodesign** [comment]
Woops my mistake. They should line up next to one another. Unless it was
facebook , tumblr, Twitter

On Saturday, March 14, 2015, Thomas Reggi notifications@github.com wrote:

> In the mockup for the social buttons you include twitter twice.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/reggi/wordpress-savory/issues/1#issuecomment-80740256
> .

## 

Gabriela d'Amato
—
(971)404-6928
g-damato.com

**Comment by reggi** [comment]
Oh it's tumblr! My bad!

**Comment by gdamatodesign** [comment]
Lol

On Saturday, March 14, 2015, Thomas Reggi notifications@github.com wrote:

> Oh it's tumblr! My bad!
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/reggi/wordpress-savory/issues/1#issuecomment-80742274
> .

## 

Gabriela d'Amato
—
(971)404-6928
g-damato.com
