### ISSUE TITLE
Events in sidebar

### ISSUE THREAD

**Issue by reggi** [reggi/wordpress-savory#11]
In the mockup there's an event address in the sidebar. Because events don't contain the actual address (they could but it would have to be added as a custom field to each event individually in addition to google calendar), I don't have this information in a post. 

What do we do here?
- Add address custom field and show address in sidebar?
- Show event post excerpt instead?

**Comment by reggi** [comment]
@gdamatodesign this too =)

**Comment by gdamatodesign** [comment]
In this case it would be better to add a custom address field. Michael's clients are bi-coastal so It would be nice for them to quickly see where ( LA/NYC) the event is!

**Comment by reggi** [comment]
uses the `address` custom field.
