### ISSUE TITLE
Search!

### ISSUE THREAD

**Issue by reggi** [reggi/wordpress-savory#12]
Wordpress search is always a big pain. Every time I've integrated search with wordpress in past projects I've made it just connect with google site search instead.

Questions.
- Do we need to use native wordpress search?
- Can we use google search?
  - If the form is submitted can we send them to google (where the search would be restricted to Michaels domain name?)
  - Or should it be embeded on the site itself?

**Comment by reggi** [comment]
@gdamatodesign thoughts on this?

**Comment by gdamatodesign** [comment]
Possible to integrate the search design on my Ai? 

Design first here - so if you can integrate my full page design and harness Michaels site content within google that seems just fine.

**Comment by reggi** [comment]
never saw your search page with content here's what i made it look like.

![screen shot 2015-03-15 at 4 53 36 am](https://cloud.githubusercontent.com/assets/296798/6655299/5e615d08-cacf-11e4-979d-1c32920f8c57.png)

**Comment by gdamatodesign** [comment]
Is this live?

Gabriela d'Amato
—
(971)404-6928
g-damato.com
