### ISSUE TITLE
Hide part of big image on permalink pages?

### ISSUE THREAD

**Issue by reggi** [reggi/wordpress-savory#14]
Instead of showing all of the big header image on the permalink pages I think it best to just show the nav with the image cropped behind it about 200px instead of what it is now at 600px.

**Comment by reggi** [comment]
@gdamatodesign thoughts on this?

**Comment by gdamatodesign** [comment]
Perfect! Great Idea - 

Also for the header image - Would it be possible to send it way back on z-index to create an effect like the one seen here ( http://www.alldayeveryday.com/ ) where the body copy overlaps the header image on scroll.
