### ISSUE TITLE
Hosting Fonts!

### ISSUE THREAD

**Issue by gdamatodesign** [reggi/wordpress-savory#15]
Sup @reggi 

https://www.dropbox.com/sh/mnw77k493jbyrdf/AAAKBgHIT_CHmLNJn0YksqXea?dl=0

Above is a link to the .otf files for Aksidenz grotesk and Perpetua. How complicated is it to host / get these fonts up on the WP? I think the design / theme will be so much cleaner with the intended typesizes and line-heights. 

GD

**Comment by reggi** [comment]
Hey! There's too many fonts in this folder, whats what? I have one serif and one sans-serif in the design. Seems like you gave me 4 fonts. Plus I don't think these are licensed web fonts, he could get in trouble, plus I could by having it in this repo. It's much easier / faster load times included to use comparable google fonts.

**Comment by reggi** [comment]
@gdamatodesign thoughts?

**Comment by reggi** [comment]
Lato / Lora

**Comment by gdamatodesign** [comment]
Update!

Body copy Lato ( Bold / Reg ) 

Serif copy Cardo (Reg / Ital )

Can this be done? Cardo would need .01em of letter spacing.

**Comment by reggi** [comment]
I believe I got this. If it's not up to snuff in a particular place, let me know.
