### ISSUE TITLE
Google Charts Update

### ISSUE THREAD

**Issue by gdamatodesign** [reggi/wordpress-savory#16]
https://docs.google.com/spreadsheets/d/1ePKf0mhXBQohg_5MV_ILR7pSLeGfDoB5epOSJ6Xsq1U/edit#gid=0

@reggi 

The chart linked above is ready for a refresh... Question: line 14 "Welcome to the other side" needs to be deleted from the chart. Unsure how to do this without messing anything up. 

The new copy references this Gdoc. 
https://docs.google.com/document/d/1HoAhwxyA2LadzaF9gM-FVufwikKP7Jz94Rh7wrul4zM/edit?usp=sharing

**Comment by reggi** [comment]
I deleted the row, will close when I import. What about `address`, as well as `event_url`. Oh and it would be much easier to set the date now for the events then later.

**Comment by gdamatodesign** [comment]
@reggi 
The chart is housing descriptions only. A Real Life event does not exist yet, thus I cant provide you with that info...

I'm getting in touch with Michael to see if he can link me to one of his up and coming events. But! could you or I set up a google cal event as a dummy in the meantime? Technically anyones google cal could be used yes?

**Comment by reggi** [comment]
I put in dummy data for both `event_url` and `address` i just updated everything.
