### ISSUE TITLE
Text Colors, Button Colors

### ISSUE THREAD

**Issue by gdamatodesign** [reggi/wordpress-savory#17]
@reggi 

![screen shot 2015-03-15 at 11 24 13 am](https://cloud.githubusercontent.com/assets/11381038/6656647/6843e246-cb06-11e4-92f1-ba23d3080e76.png)

Section Headers ( Whats Now, Subscribe here ) 
#000000

Article Heading and Date ( Same as Class Names, Private section Names ) 
#000000

Image Caption
#000000

Input Fields
#515151

Body Copy
#515151

Button Background-Color
#000000

**Comment by reggi** [comment]
- [x] Section Headers ( Whats Now, Subscribe here ) 
- [x] Article Heading and Date ( Same as Class Names, Private section Names ) 
- [x] Image Caption
- [x] Input Fields
- [x] Body Copy
- [x] Button Background-Color
