### ISSUE TITLE
Strokes.

### ISSUE THREAD

**Issue by gdamatodesign** [reggi/wordpress-savory#20]
![screen shot 2015-03-15 at 5 29 20 pm](https://cloud.githubusercontent.com/assets/11381038/6658532/3345169a-cb43-11e4-8283-27c824853135.png)

All borders / Strokes should be 1px Max.

**Comment by reggi** [comment]
2px strokes and them turning to 1px on focus was the only identifying thing for (mainly for accessibility reasons) for a user to know where the focus is. I removed it. I'm fine without having anything. Just wanted to note my reasoning.
