### ISSUE TITLE
Navigation - Fixed Position

### ISSUE THREAD

**Issue by gdamatodesign** [reggi/wordpress-savory#22]
![screen shot 2015-03-15 at 6 46 04 pm](https://cloud.githubusercontent.com/assets/11381038/6658559/cb2f9c0a-cb43-11e4-8460-cf20a262be1e.png)

Fix the nav so that the page content comes to it, then overlaps.

**Comment by reggi** [comment]
![mar 15 2015 22 13](https://cloud.githubusercontent.com/assets/296798/6659649/92bab824-cb60-11e4-80ce-65b3c42876bf.gif)
