### ISSUE TITLE
Private Session Inquiry post loading. 

### ISSUE THREAD

**Issue by gdamatodesign** [reggi/wordpress-savory#23]
![screen shot 2015-03-15 at 5 26 03 pm](https://cloud.githubusercontent.com/assets/11381038/6658571/071a7154-cb44-11e4-815f-6094a7a5bf9e.png)

After you submit an inquiry, can you eliminate this loader?

**Comment by gdamatodesign** [comment]
Copy should read "Schedule a Private Session - Submit an inquiry" 

If I can fix this let me know

**Comment by reggi** [comment]
There's redirect settings in the admin, I disabled it and the image is gone.
