### ISSUE TITLE
Align classes horizontally. 

### ISSUE THREAD

**Issue by gdamatodesign** [reggi/wordpress-savory#26]
![screen shot 2015-03-15 at 6 56 02 pm](https://cloud.githubusercontent.com/assets/11381038/6658617/602a95fc-cb45-11e4-8470-9ca1fee0290e.png)

Align Mentorship + IET just like Tarot and Energetic Clearing. 

H3 changes to 18px size

**Comment by gdamatodesign** [comment]
1px stroke

**Comment by reggi** [comment]
I'm using some fancy javascript (masonry) here to make sure they don't break all over the page. This is a good thing! If I remove it There will be massive amounts of white space breaking after those sections, this is a classic HTML stacking issue.
