### ISSUE TITLE
Workshop Copy align / Photo swap

### ISSUE THREAD

**Issue by gdamatodesign** [reggi/wordpress-savory#28]
![screen shot 2015-03-15 at 7 04 26 pm](https://cloud.githubusercontent.com/assets/11381038/6658641/34d04cb6-cb46-11e4-873f-999ea958ea08.png)

1) Title copy to 18px
2) Align copy to top of photo ( up 10px or so)
3) Replace all photography with the photos in this folder
https://www.dropbox.com/sh/fhkbjehq8yajvbw/AAAja7WgerqbyhpbkckhcXLSa?dl=0

**Comment by reggi** [comment]
- [x] Title copy to 18px
- [x]  Align copy to top of photo ( up 10px or so)
- [x] Replace all photography with the photos in this folder
