### ISSUE TITLE
Where's "subscribe" go?

### ISSUE THREAD

**Issue by reggi** [reggi/wordpress-savory#4]
There's a subscribe form on the sidebar, where does that go? Mailchimp?

![screen shot 2015-03-06 at 6 34 21 pm](https://cloud.githubusercontent.com/assets/296798/6538392/79b15e88-c42f-11e4-8714-1792a356c11e.png)

**Comment by gdamatodesign** [comment]
I believe Michael has some webmail management happening through go-daddy. However he uses google groups to send mass emails. 

What is your suggestion here?

**Comment by reggi** [comment]
Whatever service he uses should have an embedable form I can style to look like this. It doesn't matter which one. :smile:

**Comment by reggi** [comment]
@gdamatodesign Webmail management is different from newsletter management. :mailbox: :email: :100:

**Comment by reggi** [comment]
@gdamatodesign if you don't tell me what to use I'm gonna create a trial mail-chimp account for him and use that.

**Comment by gdamatodesign** [comment]
Were you able to see whats going for him via GoDaddy? He's not able to clearly let me know, but he did mention he has a mail server or something along those lines. I have no clue what the pricing looks like currently for mail chimp.  Calling him now - I'm bad at email

**Comment by gdamatodesign** [comment]
@reggi 

Mail Chimp seems like a great idea... I cant seem to find the entrepreneur pricing on their site though - do you know it off hand? 

there is also http://myemma.com/, but I don't think Michael is interested in their analytics. Does mail-chimp crunch data?
