### ISSUE TITLE
Navigation Links

### ISSUE THREAD

**Issue by reggi** [reggi/wordpress-savory#6]
Hey @gabrieladamato

Looks like you designed the navigation to work with anchor links where a link like:

```
<a href="#private-session"></a>
```

Would go to that section.

Is this true? If so then we have a problem because on a permalink page for instance that section wouldn't exist on the page.

This also means that we'd need individual pages for each one of those sections.

Let's be sure to use normal casing for better SEO.
- Header Menu
  - Michael Domitrovitch
  - What's Now?
- Header Sub-Menu
  - Private Sessions
  - Classes
  - Journeys
  - Events & Retreats

Menu's can be edited here:

http://093.db4.myftpupload.com/wp-admin/nav-menus.php

**Comment by reggi** [comment]
Menu's can be edited here 

http://093.db4.myftpupload.com/wp-admin/nav-menus.php

**Comment by reggi** [comment]
My thoughts here was that on the permalink pages we can have the other sections load under the post just as on the home page. Then the anchors always work. @gabrieladamato thoughts?

**Comment by gdamatodesign** [comment]
This has been nested on the current Nav yes?

**Comment by reggi** [comment]
These work :)
