### ISSUE TITLE
Content & Classes Buttons

### ISSUE THREAD

**Issue by reggi** [reggi/wordpress-savory#7]
So I used a Wordpress Post CSV importer to populate some of the content from a [spreadsheet in google drive](https://docs.google.com/spreadsheets/d/1ePKf0mhXBQohg_5MV_ILR7pSLeGfDoB5epOSJ6Xsq1U/edit#gid=0) (just shared it with you). That way we can decide how to best organize everything. 

We never really thought-through how we're gonna do events and where these buttons are gonna go.

![screen shot 2015-03-09 at 8 13 11 am](https://cloud.githubusercontent.com/assets/296798/6554619/31e5b11a-c634-11e4-9819-596eb4f27f9d.png)

The site is still a mess and plenty of things still don't work. You can check it out here.

http://093.db4.myftpupload.com

**Comment by gdamatodesign** [comment]
Hey let me know when you have time for a conversation!

I'm very impressed with the development of the website but I really need to
get some design elements aligned with my illustrator artboards, a big one
being typography ( hosting "aksidenz-grotesk" and "perpetua" if possible )

Talk soon!

Gabriela d'Amato
—
(971)404-6928
g-damato.com

**Comment by gdamatodesign** [comment]
Another comment on this: 

Can the class description be invisible by default and be shown onclick by selecting the class name or photo?

**Comment by reggi** [comment]
Like this? http://www.gfycat.com/BaggyAnxiousAcornbarnacle

**Comment by reggi** [comment]
This is a gif give it a second:

![baggyanxiousacornbarnacle](https://cloud.githubusercontent.com/assets/296798/6654723/12cc3bf0-caad-11e4-8c8d-f4f8cf16f92c.gif)
