### ISSUE TITLE
Next article button

### ISSUE THREAD

**Issue by reggi** [reggi/wordpress-savory#8]
On the homepage there's a next article button. The homepage has only one post, the latest one. If you are on a normal homepage for a wordpress blog you get all the recent posts and they are paginated, the first page is the homepage, you click more posts and you get page 2. Because we only have one post, each page has one post, but these pages aren't the permalink pages for the post. 

My suggestion is to show a link to the next post itself via permalink and not the page of post(s).

**Comment by gdamatodesign** [comment]
Does this mean that one will have to create that link every time the write a new post?

**Comment by reggi** [comment]
No way! It's gonna happen automatically.

**Comment by gdamatodesign** [comment]
Ok sweet
