### ISSUE TITLE
Document "event_url" custom field

### ISSUE THREAD

**Issue by reggi** [reggi/wordpress-savory#9]
Within the post for an event if you want the event button to link to a google calendar you need to create a custom field for that post with a specific name. Then set it to the google calendar url. This needs to be shared with the posters of the events in the blog.

**Comment by gdamatodesign** [comment]
Perfect, we spoke about this on Gchat...Anything else I can do to help?

**Comment by reggi** [comment]
It's simply `event_url` all we have to do is add them in I guess.
